### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by annajiat** [jgarciamesa/2021-09-10-asu-online#3]
Hi,
To reflect the rescheduled dates, we should rename the repository.
Proposed: 2021-09-10-asu-online
Current: 2021-08-02-asu-online

If required, here is the tutorial:
https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/renaming-a-repository

**Comment by jgarciamesa** [comment]
Done, thank you for the tutorial.
